using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.Data.SqlClient;
using TarimDonusum.Models;
using TarimDonusum.Tablolar;

namespace TarimDonusum.IsKurallari;

public sealed class CevreselSosyalAnketYonetimIsKurallari(IConfiguration configuration,ILogger<CevreselSosyalAnketYonetimIsKurallari> logger)
{
    private readonly string _connectionString=configuration.GetConnectionString("DefaultConnection")??"";

    public async Task<Sonuc<object>> SayfaVerisiAsync(Kullanici? k,int? surumId=null)
    {
        Sonuc<object> s=new();if(!YetkiliMi(k,s))return s;
        try{await using SqlConnection c=new(_connectionString);await c.OpenAsync();List<object> surumler=[];await using(SqlCommand q=new("SELECT Id,SurumNo,Durum,Aciklama,YayinTarihi FROM dbo.CevreselSosyalAnketSurum ORDER BY SurumNo DESC",c))await using(SqlDataReader r=await q.ExecuteReaderAsync())while(await r.ReadAsync())surumler.Add(new{id=r.GetInt32(0),surumNo=r.GetInt32(1),durum=r.GetInt32(2),aciklama=r.GetString(3),yayinTarihi=r.IsDBNull(4)?null:(DateTime?)r.GetDateTime(4)});int id=surumId??await SecilecekSurumIdAsync(c);s.nesne=new{surumler,anket=id>0?await OkuAsync(c,id):null};}catch(Exception ex){logger.LogError(ex,"ÇSVF okunamadı.");s.HataEkle("Anket bilgileri okunamadı.");}return s;
    }

    public async Task<Sonuc<int>> TaslakOlusturAsync(Kullanici? k)
    {
        Sonuc<int> s=new();if(!YetkiliMi(k,s))return s;
        try{await using SqlConnection c=new(_connectionString);await c.OpenAsync();int mevcut=await ScalarAsync(c,"SELECT ISNULL(MAX(Id),0) FROM dbo.CevreselSosyalAnketSurum WHERE Durum=0");if(mevcut>0){s.nesne=mevcut;s.mesaj="Mevcut taslak açıldı.";return s;}int kaynak=await ScalarAsync(c,"SELECT ISNULL(MAX(Id),0) FROM dbo.CevreselSosyalAnketSurum WHERE Durum=1");if(kaynak<=0){s.HataEkle("Kopyalanacak yayınlanmış anket bulunamadı.");return s;}await using SqlTransaction tr=(SqlTransaction)await c.BeginTransactionAsync();try{int yeni=await InsertAsync(c,tr,"INSERT dbo.CevreselSosyalAnketSurum(SurumNo,Durum,Aciklama,KapsamDisiFaaliyetlerBaslik,KapsamDisiFaaliyetlerHtml) OUTPUT INSERTED.Id SELECT (SELECT ISNULL(MAX(SurumNo),0)+1 FROM dbo.CevreselSosyalAnketSurum),0,N'Yeni ÇSVF taslağı',KapsamDisiFaaliyetlerBaslik,KapsamDisiFaaliyetlerHtml FROM dbo.CevreselSosyalAnketSurum WHERE Id=@Id",("@Id",kaynak));await KopyalaAsync(c,tr,kaynak,yeni);await tr.CommitAsync();s.nesne=yeni;s.mesaj="Taslak oluşturuldu.";}catch{await tr.RollbackAsync();throw;}}catch(Exception ex){logger.LogError(ex,"Taslak oluşturulamadı.");s.HataEkle("Anket taslağı oluşturulamadı.");}return s;
    }

    public async Task<Sonuc> AnketAdiniKaydetAsync(CevreselSosyalAnketAdiModeli m,Kullanici? k)
    {
        Sonuc s=new();if(!YetkiliMi(k,s))return s;if(m.id<=0||string.IsNullOrWhiteSpace(m.aciklama)){s.HataEkle("Anket adı boş olamaz.");return s;}return await GuncelleAsync(s,m.id,"UPDATE dbo.CevreselSosyalAnketSurum SET Aciklama=@Ad WHERE Id=@Id","Anket adı güncellendi.",( "@Ad",m.aciklama.Trim()));
    }

    public async Task<Sonuc> KapsamDisiKaydetAsync(CevreselSosyalKapsamDisiModeli m,Kullanici? k)
    {
        Sonuc s=new();if(!YetkiliMi(k,s))return s;string baslik=(m.baslik??"").Trim(),html=GuvenliHtml(m.html);if(m.id<=0||baslik.Length==0||html.Length==0){s.HataEkle("Başlık ve HTML içeriği boş olamaz.");return s;}return await GuncelleAsync(s,m.id,"UPDATE dbo.CevreselSosyalAnketSurum SET KapsamDisiFaaliyetlerBaslik=@Baslik,KapsamDisiFaaliyetlerHtml=@Html WHERE Id=@Id","Kapsam dışı faaliyetler güncellendi.",( "@Baslik",baslik),("@Html",html));
    }

    public async Task<Sonuc> BolumKaydetAsync(CevreselSosyalBolumKayitModeli m,Kullanici? k)
    {
        Sonuc s=new();if(!YetkiliMi(k,s))return s;if(m.anketSurumId<=0||string.IsNullOrWhiteSpace(m.kod)||string.IsNullOrWhiteSpace(m.baslik)){s.HataEkle("Bölüm numarası ve başlığı zorunludur.");return s;}
        try{await using SqlConnection c=new(_connectionString);await c.OpenAsync();if(!await DuzenlenebilirAsync(c,m.anketSurumId,s))return s;if(m.id>0)await CalistirAsync(c,null,"UPDATE dbo.CevreselSosyalAnketBolum SET Kod=@Kod,Baslik=@Baslik WHERE Id=@Id AND AnketSurumId=@Surum",("@Kod",m.kod.Trim()),("@Baslik",m.baslik.Trim()),("@Id",m.id),("@Surum",m.anketSurumId));else await CalistirAsync(c,null,"INSERT dbo.CevreselSosyalAnketBolum(AnketSurumId,Kod,Baslik,SiraNo,Aktif) SELECT @Surum,@Kod,@Baslik,ISNULL(MAX(SiraNo),0)+1,1 FROM dbo.CevreselSosyalAnketBolum WHERE AnketSurumId=@Surum",("@Surum",m.anketSurumId),("@Kod",m.kod.Trim()),("@Baslik",m.baslik.Trim()));await YenileAsync(c,m.anketSurumId);s.mesaj=m.id>0?"Bölüm güncellendi.":"Bölüm eklendi.";}catch(Exception ex){logger.LogError(ex,"Bölüm kaydedilemedi.");s.HataEkle("Bölüm kaydedilemedi. Bölüm numarası benzersiz olmalıdır.");}return s;
    }

    public Task<Sonuc> BolumSilAsync(int id,int surumId,Kullanici? k)=>SilAsync(k,surumId,id,"DELETE FROM dbo.CevreselSosyalAnketBolum WHERE Id=@Id AND AnketSurumId=@Surum","Bölüm ve bağlı soruları silindi.");

    public async Task<Sonuc> SoruKaydetAsync(CevreselSosyalSoruKayitModeli m,Kullanici? k)
    {
        Sonuc sonuc=new();if(!YetkiliMi(k,sonuc))return sonuc;var s=m.soru;if(m.anketSurumId<=0||m.bolumId<=0||string.IsNullOrWhiteSpace(s.gorunumKodu)||string.IsNullOrWhiteSpace(s.metin)){sonuc.HataEkle("Bölüm, soru numarası ve soru metni zorunludur.");return sonuc;}if(!s.ortak&&!s.yapim&&!s.guncelleme){sonuc.HataEkle("Soru en az bir yatırım bağlamında gösterilmelidir.");return sonuc;}if(string.IsNullOrWhiteSpace(s.anahtar))s.anahtar=$"soru_{Guid.NewGuid():N}";
        try{await using SqlConnection c=new(_connectionString);await c.OpenAsync();if(!await DuzenlenebilirAsync(c,m.anketSurumId,sonuc))return sonuc;if(await ScalarAsync(c,"SELECT COUNT(*) FROM dbo.CevreselSosyalAnketBolum WHERE Id=@Bolum AND AnketSurumId=@Surum",("@Bolum",m.bolumId),("@Surum",m.anketSurumId))==0){sonuc.HataEkle("Seçilen bölüm bu ankete ait değil.");return sonuc;}await using SqlTransaction tr=(SqlTransaction)await c.BeginTransactionAsync();try{if(s.kapsamDisiFaaliyetlerListesiniGoster)await CalistirAsync(c,tr,"UPDATE S SET KapsamDisiFaaliyetlerListesiniGosterMi=0 FROM dbo.CevreselSosyalAnketSoru S INNER JOIN dbo.CevreselSosyalAnketBolum B ON B.Id=S.BolumId WHERE B.AnketSurumId=@Surum AND S.Id<>@Id",("@Surum",m.anketSurumId),("@Id",s.id));(string,object)[] p=SoruParametreleri(m.bolumId,s);if(s.id>0)await CalistirAsync(c,tr,@"UPDATE S SET BolumId=@Bolum,Anahtar=@Anahtar,GorunumKodu=@Kod,Baslik=@Baslik,Metin=@Metin,CevapTuru=@Tur,CevapBaglami=@Baglam,YapimIsindeGoster=@Yapim,GuncellemeIsindeGoster=@Guncelleme,ZorunluMu=@Zorunlu,MaksimumUzunluk=@Maks,NotMetni=@Not,BilgiMetni=@Bilgi,YerTutucu=@Yer,KapsamDisiBirakirMi=@Kapsam,KapsamDisiFaaliyetlerListesiniGosterMi=@Liste,HerZamanAciklamaIste=@Aciklama,OtomatikKaynakKodu=@Kaynak,Aktif=@Aktif FROM dbo.CevreselSosyalAnketSoru S INNER JOIN dbo.CevreselSosyalAnketBolum B ON B.Id=S.BolumId WHERE S.Id=@Id AND B.AnketSurumId=@Surum",[..p,("@Id",s.id),("@Surum",m.anketSurumId)]);else s.id=await InsertAsync(c,tr,@"INSERT dbo.CevreselSosyalAnketSoru(BolumId,Anahtar,GorunumKodu,Baslik,Metin,CevapTuru,CevapBaglami,YapimIsindeGoster,GuncellemeIsindeGoster,ZorunluMu,MaksimumUzunluk,NotMetni,BilgiMetni,YerTutucu,KapsamDisiBirakirMi,KapsamDisiFaaliyetlerListesiniGosterMi,HerZamanAciklamaIste,OtomatikKaynakKodu,SiraNo,Aktif) OUTPUT INSERTED.Id SELECT @Bolum,@Anahtar,@Kod,@Baslik,@Metin,@Tur,@Baglam,@Yapim,@Guncelleme,@Zorunlu,@Maks,@Not,@Bilgi,@Yer,@Kapsam,@Liste,@Aciklama,@Kaynak,ISNULL(MAX(SiraNo),0)+1,@Aktif FROM dbo.CevreselSosyalAnketSoru WHERE BolumId=@Bolum",p);await AltKayitlariYazAsync(c,tr,s);await tr.CommitAsync();}catch{await tr.RollbackAsync();throw;}await YenileAsync(c,m.anketSurumId);sonuc.mesaj="Soru kaydedildi.";}catch(Exception ex){logger.LogError(ex,"Soru kaydedilemedi.");sonuc.HataEkle("Soru kaydedilemedi. Soru anahtarı ve numarası benzersiz olmalıdır.");}return sonuc;
    }

    public Task<Sonuc> SoruSilAsync(int id,int surumId,Kullanici? k)=>SilAsync(k,surumId,id,"DELETE S FROM dbo.CevreselSosyalAnketSoru S INNER JOIN dbo.CevreselSosyalAnketBolum B ON B.Id=S.BolumId WHERE S.Id=@Id AND B.AnketSurumId=@Surum","Soru silindi.");

    public async Task<Sonuc> YayinlaAsync(int id,Kullanici? k)
    {
        Sonuc s=new();if(!YetkiliMi(k,s))return s;try{await using SqlConnection c=new(_connectionString);await c.OpenAsync();if(await ScalarAsync(c,"SELECT COUNT(*) FROM dbo.CevreselSosyalAnketSurum WHERE Id=@Id AND Durum=0",("@Id",id))==0){s.HataEkle("Yayınlanacak taslak bulunamadı.");return s;}await using SqlTransaction tr=(SqlTransaction)await c.BeginTransactionAsync();try{await CalistirAsync(c,tr,"UPDATE dbo.CevreselSosyalAnketSurum SET Durum=2 WHERE Durum=1;UPDATE dbo.CevreselSosyalAnketSurum SET Durum=1,YayinTarihi=SYSDATETIME() WHERE Id=@Id",("@Id",id));await tr.CommitAsync();}catch{await tr.RollbackAsync();throw;}await YenileAsync(c,id);s.mesaj="Anket yayınlandı.";}catch(Exception ex){logger.LogError(ex,"Anket yayınlanamadı.");s.HataEkle("Anket yayınlanamadı.");}return s;
    }

    private static async Task<CevreselSosyalAnketDuzenlemeModeli?> OkuAsync(SqlConnection c,int id)
    {
        CevreselSosyalAnketDuzenlemeModeli? m=null;await using(SqlCommand q=new("SELECT Id,SurumNo,Durum,Aciklama,ISNULL(KapsamDisiFaaliyetlerBaslik,N''),ISNULL(KapsamDisiFaaliyetlerHtml,N'') FROM dbo.CevreselSosyalAnketSurum WHERE Id=@Id",c)){q.Parameters.AddWithValue("@Id",id);await using SqlDataReader r=await q.ExecuteReaderAsync();if(await r.ReadAsync())m=new(){id=r.GetInt32(0),surumNo=r.GetInt32(1),durum=r.GetInt32(2),aciklama=r.GetString(3),kapsamDisiFaaliyetlerBaslik=r.GetString(4),kapsamDisiFaaliyetlerHtml=r.GetString(5)};}if(m==null)return null;List<CevreselSosyalBolumDuzenlemeModeli> bs=[];await using(SqlCommand q=new("SELECT Id,Kod,Baslik,SiraNo FROM dbo.CevreselSosyalAnketBolum WHERE AnketSurumId=@Id AND Aktif=1 ORDER BY SiraNo,Id",c)){q.Parameters.AddWithValue("@Id",id);await using SqlDataReader r=await q.ExecuteReaderAsync();while(await r.ReadAsync())bs.Add(new(){id=r.GetInt32(0),kod=r.GetString(1),baslik=r.GetString(2),siraNo=r.GetInt32(3)});}foreach(var b in bs){await BilgileriOkuAsync(c,b);await SorulariOkuAsync(c,b);m.bolumler.Add(b);}return m;
    }

    private static async Task BilgileriOkuAsync(SqlConnection c,CevreselSosyalBolumDuzenlemeModeli b){await using SqlCommand q=new("SELECT Id,Tur,Baslik,Metin,MaddelerJson FROM dbo.CevreselSosyalAnketBilgi WHERE BolumId=@Id AND Aktif=1 ORDER BY SiraNo,Id",c);q.Parameters.AddWithValue("@Id",b.id);await using SqlDataReader r=await q.ExecuteReaderAsync();while(await r.ReadAsync())b.bilgiler.Add(new(){id=r.GetInt32(0),tur=r.GetString(1),baslik=r.IsDBNull(2)?null:r.GetString(2),metin=r.IsDBNull(3)?null:r.GetString(3),maddeler=r.IsDBNull(4)?[]:JsonSerializer.Deserialize<List<string>>(r.GetString(4))??[]});}
    private static async Task SorulariOkuAsync(SqlConnection c,CevreselSosyalBolumDuzenlemeModeli b)
    {
        List<CevreselSosyalSoruDuzenlemeModeli> ss=[];await using(SqlCommand q=new(@"SELECT Id,Anahtar,GorunumKodu,Baslik,Metin,CevapTuru,CevapBaglami,YapimIsindeGoster,GuncellemeIsindeGoster,ZorunluMu,MaksimumUzunluk,NotMetni,BilgiMetni,YerTutucu,KapsamDisiBirakirMi,HerZamanAciklamaIste,SiraNo,OtomatikKaynakKodu,Aktif,KapsamDisiFaaliyetlerListesiniGosterMi FROM dbo.CevreselSosyalAnketSoru WHERE BolumId=@Id ORDER BY SiraNo,Id",c)){q.Parameters.AddWithValue("@Id",b.id);await using SqlDataReader r=await q.ExecuteReaderAsync();while(await r.ReadAsync())ss.Add(new(){id=r.GetInt32(0),bolumId=b.id,anahtar=r.GetString(1),gorunumKodu=r.GetString(2),baslik=r.GetString(3),metin=r.GetString(4),cevapTuru=r.GetString(5),ortak=r.GetInt32(6)==1,yapim=r.GetBoolean(7),guncelleme=r.GetBoolean(8),zorunlu=r.GetBoolean(9),maksimumUzunluk=r.IsDBNull(10)?null:r.GetInt32(10),notMetni=r.IsDBNull(11)?null:r.GetString(11),bilgiMetni=r.IsDBNull(12)?null:r.GetString(12),yerTutucu=r.IsDBNull(13)?null:r.GetString(13),kapsamDisiBirakir=r.GetBoolean(14),herZamanAciklamaIste=r.GetBoolean(15),siraNo=r.GetInt32(16),otomatikKaynakKodu=r.IsDBNull(17)?null:r.GetString(17),aktif=r.GetBoolean(18),kapsamDisiFaaliyetlerListesiniGoster=r.GetBoolean(19)});}foreach(var x in ss){await using SqlCommand q=new("SELECT Deger,0,0,SiraNo FROM dbo.CevreselSosyalAnketSoruSecenek WHERE SoruId=@Id AND Aktif=1 UNION ALL SELECT SecenekDegeri,CASE WHEN AciklamaIstensinMi=1 THEN 1 ELSE 0 END,CASE WHEN DosyaIstensinMi=1 THEN 1 ELSE 0 END,10000+SiraNo FROM dbo.CevreselSosyalAnketSoruKosul WHERE SoruId=@Id ORDER BY SiraNo",c);q.Parameters.AddWithValue("@Id",x.id);await using SqlDataReader r=await q.ExecuteReaderAsync();while(await r.ReadAsync()){string d=r.GetString(0);bool a=r.GetInt32(1)==1,f=r.GetInt32(2)==1;if(!a&&!f)x.secenekler.Add(d);if(a)x.aciklamaKosullari.Add(d);if(f)x.dosyaKosullari.Add(d);}b.sorular.Add(x);}}
    private static async Task KopyalaAsync(SqlConnection c,SqlTransaction tr,int kaynak,int yeni)
    {
        List<(int id,string kod,string baslik,object aciklama,int sira,bool aktif)> bs=[];await using(SqlCommand q=new("SELECT Id,Kod,Baslik,Aciklama,SiraNo,Aktif FROM dbo.CevreselSosyalAnketBolum WHERE AnketSurumId=@Id",c,tr)){q.Parameters.AddWithValue("@Id",kaynak);await using SqlDataReader r=await q.ExecuteReaderAsync();while(await r.ReadAsync())bs.Add((r.GetInt32(0),r.GetString(1),r.GetString(2),r.IsDBNull(3)?DBNull.Value:r.GetString(3),r.GetInt32(4),r.GetBoolean(5)));}foreach(var b in bs){int bid=await InsertAsync(c,tr,"INSERT dbo.CevreselSosyalAnketBolum(AnketSurumId,Kod,Baslik,Aciklama,SiraNo,Aktif) OUTPUT INSERTED.Id VALUES(@Surum,@Kod,@Baslik,@Aciklama,@Sira,@Aktif)",( "@Surum",yeni),("@Kod",b.kod),("@Baslik",b.baslik),("@Aciklama",b.aciklama),("@Sira",b.sira),("@Aktif",b.aktif));await CalistirAsync(c,tr,"INSERT dbo.CevreselSosyalAnketBilgi(BolumId,Tur,Baslik,Metin,MaddelerJson,SiraNo,Aktif) SELECT @Yeni,Tur,Baslik,Metin,MaddelerJson,SiraNo,Aktif FROM dbo.CevreselSosyalAnketBilgi WHERE BolumId=@Eski",("@Yeni",bid),("@Eski",b.id));List<int> ids=[];await using(SqlCommand q=new("SELECT Id FROM dbo.CevreselSosyalAnketSoru WHERE BolumId=@Id",c,tr)){q.Parameters.AddWithValue("@Id",b.id);await using SqlDataReader r=await q.ExecuteReaderAsync();while(await r.ReadAsync())ids.Add(r.GetInt32(0));}foreach(int sid in ids){int ns=await InsertAsync(c,tr,@"INSERT dbo.CevreselSosyalAnketSoru(BolumId,Anahtar,GorunumKodu,Baslik,Metin,CevapTuru,CevapBaglami,YapimIsindeGoster,GuncellemeIsindeGoster,ZorunluMu,MaksimumUzunluk,NotMetni,BilgiMetni,YerTutucu,KapsamDisiBirakirMi,KapsamDisiFaaliyetlerListesiniGosterMi,HerZamanAciklamaIste,OtomatikKaynakKodu,SiraNo,Aktif) OUTPUT INSERTED.Id SELECT @Bolum,Anahtar,GorunumKodu,Baslik,Metin,CevapTuru,CevapBaglami,YapimIsindeGoster,GuncellemeIsindeGoster,ZorunluMu,MaksimumUzunluk,NotMetni,BilgiMetni,YerTutucu,KapsamDisiBirakirMi,KapsamDisiFaaliyetlerListesiniGosterMi,HerZamanAciklamaIste,OtomatikKaynakKodu,SiraNo,Aktif FROM dbo.CevreselSosyalAnketSoru WHERE Id=@Eski",("@Bolum",bid),("@Eski",sid));await CalistirAsync(c,tr,"INSERT dbo.CevreselSosyalAnketSoruSecenek(SoruId,Deger,Metin,SiraNo,Aktif) SELECT @Yeni,Deger,Metin,SiraNo,Aktif FROM dbo.CevreselSosyalAnketSoruSecenek WHERE SoruId=@Eski;INSERT dbo.CevreselSosyalAnketSoruKosul(SoruId,SecenekDegeri,AciklamaIstensinMi,DosyaIstensinMi,SiraNo) SELECT @Yeni,SecenekDegeri,AciklamaIstensinMi,DosyaIstensinMi,SiraNo FROM dbo.CevreselSosyalAnketSoruKosul WHERE SoruId=@Eski",("@Yeni",ns),("@Eski",sid));}}}

    private static (string,object)[] SoruParametreleri(int bolum,CevreselSosyalSoruDuzenlemeModeli s)=>[("@Bolum",bolum),("@Anahtar",s.anahtar.Trim()),("@Kod",s.gorunumKodu.Trim()),("@Baslik",s.baslik??""),("@Metin",s.metin.Trim()),("@Tur",s.cevapTuru),("@Baglam",s.ortak?1:2),("@Yapim",s.ortak||s.yapim),("@Guncelleme",s.ortak||s.guncelleme),("@Zorunlu",s.zorunlu),("@Maks",(object?)s.maksimumUzunluk??DBNull.Value),("@Not",(object?)s.notMetni??DBNull.Value),("@Bilgi",(object?)s.bilgiMetni??DBNull.Value),("@Yer",(object?)s.yerTutucu??DBNull.Value),("@Kapsam",s.kapsamDisiBirakir),("@Liste",s.kapsamDisiFaaliyetlerListesiniGoster),("@Aciklama",s.herZamanAciklamaIste),("@Kaynak",(object?)s.otomatikKaynakKodu??DBNull.Value),("@Aktif",s.aktif)];
    private static async Task AltKayitlariYazAsync(SqlConnection c,SqlTransaction tr,CevreselSosyalSoruDuzenlemeModeli s){await CalistirAsync(c,tr,"DELETE FROM dbo.CevreselSosyalAnketSoruSecenek WHERE SoruId=@Id;DELETE FROM dbo.CevreselSosyalAnketSoruKosul WHERE SoruId=@Id",("@Id",s.id));int n=0;foreach(string x in s.secenekler.Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct())await CalistirAsync(c,tr,"INSERT dbo.CevreselSosyalAnketSoruSecenek(SoruId,Deger,Metin,SiraNo,Aktif) VALUES(@Id,@Deger,@Deger,@Sira,1)",( "@Id",s.id),("@Deger",x.Trim()),("@Sira",++n));n=0;foreach(string x in s.aciklamaKosullari.Concat(s.dosyaKosullari).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase))await CalistirAsync(c,tr,"INSERT dbo.CevreselSosyalAnketSoruKosul(SoruId,SecenekDegeri,AciklamaIstensinMi,DosyaIstensinMi,SiraNo) VALUES(@Id,@Deger,@Aciklama,@Dosya,@Sira)",( "@Id",s.id),("@Deger",x.Trim()),("@Aciklama",s.aciklamaKosullari.Contains(x,StringComparer.OrdinalIgnoreCase)),("@Dosya",s.dosyaKosullari.Contains(x,StringComparer.OrdinalIgnoreCase)),("@Sira",++n));}
    private async Task<Sonuc> GuncelleAsync(Sonuc s,int id,string sql,string mesaj,params (string,object)[] p){try{await using SqlConnection c=new(_connectionString);await c.OpenAsync();if(!await DuzenlenebilirAsync(c,id,s))return s;await CalistirAsync(c,null,sql,[..p,("@Id",id)]);await YenileAsync(c,id);s.mesaj=mesaj;}catch(Exception ex){logger.LogError(ex,"ÇSVF güncellenemedi.");s.HataEkle("Bilgiler güncellenemedi.");}return s;}
    private async Task<Sonuc> SilAsync(Kullanici? k,int surum,int id,string sql,string mesaj){Sonuc s=new();if(!YetkiliMi(k,s))return s;try{await using SqlConnection c=new(_connectionString);await c.OpenAsync();if(!await DuzenlenebilirAsync(c,surum,s))return s;await CalistirAsync(c,null,sql,("@Id",id),("@Surum",surum));await YenileAsync(c,surum);s.mesaj=mesaj;}catch(Exception ex){logger.LogError(ex,"ÇSVF kaydı silinemedi.");s.HataEkle("Kayıt silinemedi.");}return s;}
    private static string GuvenliHtml(string? html){string x=Regex.Replace(html??"",@"<(script|style)[^>]*>.*?</\1>","",RegexOptions.IgnoreCase|RegexOptions.Singleline);HashSet<string> izinli=["p","ul","ol","li","strong","em","br","h4","h5"];return Regex.Replace(x,@"</?([a-zA-Z0-9]+)(?:\s[^>]*)?>",m=>{string e=m.Groups[1].Value.ToLowerInvariant();if(!izinli.Contains(e))return "";return e=="br"?"<br>":m.Value.StartsWith("</",StringComparison.Ordinal)?$"</{e}>":$"<{e}>";}).Trim();}
    private static bool YetkiliMi(Kullanici? k,Sonuc s){if(k?.Yetkiler.Any(x=>x.Rol==KullaniciRol.SistemYoneticisi)==true)return true;s.HataEkle("Bu işlem için sistem yöneticisi yetkisi gereklidir.");return false;}
    private static async Task<bool> DuzenlenebilirAsync(SqlConnection c,int id,Sonuc s){int d=await ScalarAsync(c,"SELECT ISNULL(MAX(Durum),-1) FROM dbo.CevreselSosyalAnketSurum WHERE Id=@Id",("@Id",id));if(d is 0 or 1)return true;s.HataEkle("Arşivlenmiş anket düzenlenemez.");return false;}
    private static async Task YenileAsync(SqlConnection c,int id){if(await ScalarAsync(c,"SELECT COUNT(*) FROM dbo.CevreselSosyalAnketSurum WHERE Id=@Id AND Durum=1",("@Id",id))==0)return;var x=await new TABCevreselSosyalAnket(c).YayindakiSurumuOkuAsync();if(x!=null)CevreselSosyalAnketTanimSaglayici.Guncelle(x);}
    private static async Task<int> SecilecekSurumIdAsync(SqlConnection c){int x=await ScalarAsync(c,"SELECT ISNULL(MAX(Id),0) FROM dbo.CevreselSosyalAnketSurum WHERE Durum=0");return x>0?x:await ScalarAsync(c,"SELECT ISNULL(MAX(Id),0) FROM dbo.CevreselSosyalAnketSurum WHERE Durum=1");}
    private static async Task<int> ScalarAsync(SqlConnection c,string sql,params (string,object)[] p){await using SqlCommand q=new(sql,c);foreach(var x in p)q.Parameters.AddWithValue(x.Item1,x.Item2);return Convert.ToInt32(await q.ExecuteScalarAsync());}
    private static async Task<int> InsertAsync(SqlConnection c,SqlTransaction tr,string sql,params (string,object)[] p){await using SqlCommand q=new(sql,c,tr);foreach(var x in p)q.Parameters.AddWithValue(x.Item1,x.Item2??DBNull.Value);return Convert.ToInt32(await q.ExecuteScalarAsync());}
    private static async Task CalistirAsync(SqlConnection c,SqlTransaction? tr,string sql,params (string,object)[] p){await using SqlCommand q=new(sql,c,tr);foreach(var x in p)q.Parameters.AddWithValue(x.Item1,x.Item2??DBNull.Value);await q.ExecuteNonQueryAsync();}
}
