/*
    NACE Rev. 2.1 - dÃ¶rt haneli sÄ±nÄ±flar (651 kayÄ±t)
    Kaynak: TÃ¼rkiye Ä°statistik Kurumu SÄ±nÄ±flama Sunucusu
    SÃ¼rÃ¼m: Avrupa TopluluÄŸunda Ekonomik Faaliyetlerin Ä°statistiki SÄ±nÄ±flamasÄ±, NACE Rev. 2.1
    Kaynak sÃ¼rÃ¼m kimliÄŸi: 1438
    Kaynak adresi: https://siniflama.tuik.gov.tr/Classifications/GetSiniflamaSatir?surumId=1438&seviye=4&kod=
    Ãœretim zamanÄ±: 2026-09-19 14:15:17 +03:00

    Betik tekrar Ã§alÄ±ÅŸtÄ±rÄ±labilir; Kod alanÄ±nda mevcut olan kayÄ±tlarÄ± atlar.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

INSERT INTO dbo.Nace (Kod, Ad, Aktif)
SELECT kaynak.Kod, kaynak.Ad, kaynak.Aktif
FROM (VALUES
    (N'01.11', N'Tahılların (pirinç hariç), baklagillerin ve yağlı tohumların yetiştirilmesi', 1),
    (N'01.12', N'Çeltik (kabuklu pirinç) yetiştirilmesi', 1),
    (N'01.13', N'Sebze, kavun-karpuz, kök ve yumru sebzelerin yetiştirilmesi', 1),
    (N'01.14', N'Şeker kamışı yetiştirilmesi', 1),
    (N'01.15', N'Tütün yetiştirilmesi', 1),
    (N'01.16', N'Lifli bitkilerin yetiştirilmesi', 1),
    (N'01.19', N'Tek yıllık (uzun ömürlü olmayan) diğer bitkisel ürünlerin yetiştirilmesi', 1),
    (N'01.21', N'Üzüm yetiştirilmesi', 1),
    (N'01.22', N'Tropikal ve subtropikal meyvelerin yetiştirilmesi', 1),
    (N'01.23', N'Turunçgillerin yetiştirilmesi', 1),
    (N'01.24', N'Yumuşak çekirdekli meyvelerin ve sert çekirdekli meyvelerin yetiştirilmesi', 1),
    (N'01.25', N'Diğer ağaç ve çalı meyvelerinin ve sert kabuklu meyvelerin yetiştirilmesi', 1),
    (N'01.26', N'Yağlı meyvelerin yetiştirilmesi', 1),
    (N'01.27', N'İçecek üretiminde kullanılan bitkisel ürünlerin yetiştirilmesi', 1),
    (N'01.28', N'Baharatlık, aromatik (ıtırlı), uyuşturucu nitelikte ve farmasötik (eczacılıkla ilgili) bitkisel ürünlerin yetiştirilmesi', 1),
    (N'01.29', N'Diğer çok yıllık (uzun ömürlü) bitkisel ürünlerin yetiştirilmesi', 1),
    (N'01.30', N'Dikim için bitki yetiştirilmesi', 1),
    (N'01.41', N'Sütü sağılan büyükbaş hayvan yetiştiriciliği', 1),
    (N'01.42', N'Diğer sığır ve manda yetiştiriciliği', 1),
    (N'01.43', N'At ve at benzeri diğer hayvan yetiştiriciliği', 1),
    (N'01.44', N'Deve ve devegillerin yetiştiriciliği', 1),
    (N'01.45', N'Koyun ve keçi yetiştiriciliği', 1),
    (N'01.46', N'Domuz yetiştiriciliği', 1),
    (N'01.47', N'Kümes hayvanları yetiştiriciliği', 1),
    (N'01.48', N'Diğer hayvan yetiştiriciliği', 1),
    (N'01.50', N'Karma çiftçilik', 1),
    (N'01.61', N'Bitkisel üretimi destekleyici faaliyetler', 1),
    (N'01.62', N'Hayvan üretimini destekleyici faaliyetler', 1),
    (N'01.63', N'Hasat sonrası bitkisel ürünler ile ilgili faaliyetler ve çoğaltma için tohumun işlenmesi', 1),
    (N'01.70', N'Avcılık, tuzakla avlanma ve ilgili hizmet faaliyetleri', 1),
    (N'02.10', N'Orman yetiştirme (silvikültür) ve diğer ormancılık faaliyetleri', 1),
    (N'02.20', N'Endüstriyel ve yakacak odun üretimi', 1),
    (N'02.30', N'Tabii olarak yetişen odun dışı orman ürünlerinin toplanması', 1),
    (N'02.40', N'Ormancılık için destekleyici faaliyetler', 1),
    (N'03.11', N'Deniz balıkçılığı', 1),
    (N'03.12', N'Tatlı su balıkçılığı', 1),
    (N'03.21', N'Deniz ürünleri yetiştiriciliği', 1),
    (N'03.22', N'Tatlı su ürünleri yetiştiriciliği', 1),
    (N'03.30', N'Balıkçılık ve su ürünleri yetiştiriciliği için destekleyici faaliyetler', 1),
    (N'05.10', N'Taş kömürü madenciliği', 1),
    (N'05.20', N'Linyit madenciliği', 1),
    (N'06.10', N'Ham petrol çıkarımı', 1),
    (N'06.20', N'Doğal gaz çıkarımı', 1),
    (N'07.10', N'Demir cevherleri madenciliği', 1),
    (N'07.21', N'Uranyum ve toryum cevherleri madenciliği', 1),
    (N'07.29', N'Diğer demir dışı metal cevherleri madenciliği', 1),
    (N'08.11', N'Süs taşı, kireç taşı, alçı taşı, arduvaz ve diğer taşların taş ocakçılığı', 1),
    (N'08.12', N'Çakıl ve kum ocaklarının işletilmesi ve kil ve kaolin madenciliği', 1),
    (N'08.91', N'Kimyasal ve gübreleme amaçlı mineral madenciliği', 1),
    (N'08.92', N'Turba çıkarımı', 1),
    (N'08.93', N'Tuz çıkarımı', 1),
    (N'08.99', N'Başka yerde sınıflandırılmamış diğer madencilik ve taş ocakçılığı', 1),
    (N'09.10', N'Petrol ve doğal gaz çıkarımını destekleyici faaliyetler', 1),
    (N'09.90', N'Madencilik ve taş ocakçılığını destekleyici diğer faaliyetler', 1),
    (N'10.11', N'Etin işlenmesi ve saklanması (mezbahacılık) (kümes hayvanlarının eti hariç)', 1),
    (N'10.12', N'Kümes hayvanları etlerinin işlenmesi ve saklanması', 1),
    (N'10.13', N'Et ve kümes hayvanları etlerinden üretilen ürünlerin imalatı', 1),
    (N'10.20', N'Balık, kabuklu deniz hayvanları ve yumuşakçaların işlenmesi ve saklanması', 1),
    (N'10.31', N'Patatesin işlenmesi ve saklanması', 1),
    (N'10.32', N'Sebze ve meyve suyu imalatı', 1),
    (N'10.39', N'Meyve ve sebzelerin diğer şekillerde işlenmesi ve korunması', 1),
    (N'10.41', N'Sıvı ve katı yağ imalatı', 1),
    (N'10.42', N'Margarin ve benzeri yenilebilir katı yağların imalatı', 1),
    (N'10.51', N'Süt ürünleri imalatı', 1),
    (N'10.52', N'Dondurma ve diğer yenilebilir buzların imalatı', 1),
    (N'10.61', N'Öğütülmüş hububat ve sebze ürünleri imalatı', 1),
    (N'10.62', N'Nişasta ve nişastalı ürünlerin imalatı', 1),
    (N'10.71', N'Ekmek, taze pastane ürünleri ve taze kek imalatı', 1),
    (N'10.72', N'Peksimet, bisküvi, dayanıklı pastane ürünleri ve kek imalatı', 1),
    (N'10.73', N'Makarna, şehriye, kuskus ve benzeri unlu mamullerin imalatı', 1),
    (N'10.81', N'Şeker imalatı', 1),
    (N'10.82', N'Kakao, çikolata ve şekerleme imalatı', 1),
    (N'10.83', N'Kahve ve çayın işlenmesi', 1),
    (N'10.84', N'Baharat, sos, sirke ve diğer çeşni maddelerinin imalatı', 1),
    (N'10.85', N'Hazır yemeklerin imalatı', 1),
    (N'10.86', N'Homojenize gıda müstahzarları ve diyetetik gıdaların imalatı', 1),
    (N'10.89', N'Başka yerde sınıflandırılmamış diğer gıda maddelerinin imalatı', 1),
    (N'10.91', N'Çiftlik hayvanları için hazır yem imalatı', 1),
    (N'10.92', N'Ev hayvanları için hazır gıda imalatı', 1),
    (N'11.01', N'Alkollü içeceklerin damıtılması, arıtılması ve harmanlanması', 1),
    (N'11.02', N'Üzümden şarap imalatı', 1),
    (N'11.03', N'Elma şarabı ve diğer fermente meyve içeceklerinin imalatı', 1),
    (N'11.04', N'Diğer damıtılmamış fermente içeceklerin imalatı', 1),
    (N'11.05', N'Bira imalatı', 1),
    (N'11.06', N'Malt imalatı', 1),
    (N'11.07', N'Alkolsüz içecek ve şişelenmiş su imalatı', 1),
    (N'12.00', N'Tütün ürünleri imalatı', 1),
    (N'13.10', N'Tekstil elyafının hazırlanması ve bükülmesi', 1),
    (N'13.20', N'Dokuma', 1),
    (N'13.30', N'Tekstil ürünlerinin bitirilmesi', 1),
    (N'13.91', N'Örgü (triko) veya tığ işi (kroşe) kumaşların imalatı', 1),
    (N'13.92', N'Ev tekstili ve hazır mefruşat ürünleri imalatı', 1),
    (N'13.93', N'Halı ve kilim imalatı', 1),
    (N'13.94', N'Halat, urgan, kınnap ve ağ imalatı', 1),
    (N'13.95', N'Dokusuz kumaşların ve dokusuz kumaştan yapılan ürünlerin imalatı', 1),
    (N'13.96', N'Diğer teknik ve endüstriyel tekstillerin imalatı', 1),
    (N'13.99', N'Başka yerde sınıflandırılmamış diğer tekstillerin imalatı', 1),
    (N'14.10', N'Örme (trikotaj) ve tığ işi (kroşe) giyim eşyası imalatı', 1),
    (N'14.21', N'Dış giyim imalatı', 1),
    (N'14.22', N'İç giyim imalatı', 1),
    (N'14.23', N'İş giysisi imalatı', 1),
    (N'14.24', N'Deri giysi ve kürk giysi imalatı', 1),
    (N'14.29', N'Başka yerde sınıflandırılmamış diğer giyim eşyası ve aksesuarların imalatı', 1),
    (N'15.11', N'Deri ve kürkün tabaklanması, işlenmesi ve boyanması', 1),
    (N'15.12', N'Bavul, el çantası, saraçlık ve koşum takımı imalatı (her tür malzemeden)', 1),
    (N'15.20', N'Ayakkabı, bot, terlik vb. imalatı', 1),
    (N'16.11', N'Ağaçların biçilmesi ve planyalanması', 1),
    (N'16.12', N'Ahşabın işlenmesi ve bitirilmesi', 1),
    (N'16.21', N'Ahşap kaplama paneli ve ağaç esaslı panel imalatı', 1),
    (N'16.22', N'Birleştirilmiş parke yer döşemelerinin imalatı', 1),
    (N'16.23', N'Diğer bina doğramacılığı ve marangozluk ürünlerinin imalatı', 1),
    (N'16.24', N'Ahşap konteyner imalatı', 1),
    (N'16.25', N'Ahşap kapı ve pencere imalatı', 1),
    (N'16.26', N'Bitkisel biyokütleden katı yakıt imalatı', 1),
    (N'16.27', N'Ahşap ürünlerin bitirilmesi', 1),
    (N'16.28', N'Diğer ağaç ürünleri imalatı; mantardan, saz, saman ve benzeri örme malzemelerinden yapılmış ürünlerin imalatı', 1),
    (N'17.11', N'Kağıt hamuru imalatı', 1),
    (N'17.12', N'Kağıt ve mukavva imalatı', 1),
    (N'17.21', N'Oluklu kağıt ve mukavva imalatı ile kağıt ve mukavvadan yapılan muhafazaların imalatı', 1),
    (N'17.22', N'Kağıttan yapılan ev eşyası, sıhhi malzemeler ve tuvalet malzemeleri imalatı', 1),
    (N'17.23', N'Kağıt kırtasiye ürünleri imalatı', 1),
    (N'17.24', N'Duvar kağıdı imalatı', 1),
    (N'17.25', N'Kağıt ve mukavvadan diğer ürünlerin imalatı', 1),
    (N'18.11', N'Gazetelerin basımı', 1),
    (N'18.12', N'Diğer matbaacılık', 1),
    (N'18.13', N'Basım ve yayım öncesi hizmetler', 1),
    (N'18.14', N'Ciltçilik ve ilgili hizmetler', 1),
    (N'18.20', N'Kayıtlı medyanın çoğaltılması', 1),
    (N'19.10', N'Kok fırını ürünlerinin imalatı', 1),
    (N'19.20', N'Rafine edilmiş petrol ve fosil yakıt ürünleri imalatı', 1),
    (N'20.11', N'Sanayi gazları imalatı', 1),
    (N'20.12', N'Boya maddeleri ve pigment imalatı', 1),
    (N'20.13', N'Diğer inorganik temel kimyasal maddelerin imalatı', 1),
    (N'20.14', N'Diğer organik temel kimyasalların imalatı', 1),
    (N'20.15', N'Kimyasal gübre ve azot bileşiklerinin imalatı', 1),
    (N'20.16', N'Birincil formda plastik ham maddelerin imalatı', 1),
    (N'20.17', N'Birincil formda sentetik kauçuk imalatı', 1),
    (N'20.20', N'Haşere ilaçları, dezenfektanlar ve diğer zirai-kimyasal ürünlerin imalatı', 1),
    (N'20.30', N'Boya, vernik ve benzeri kaplayıcı maddeler ile matbaa mürekkebi ve macun imalatı', 1),
    (N'20.41', N'Sabun ve deterjan ile temizlik ve parlatıcı preparatlarının (müstahzarlarının) imalatı', 1),
    (N'20.42', N'Parfümlerin, kozmetiklerin ve kişisel bakım preparatlarının (müstahzarlarının) imalatı', 1),
    (N'20.51', N'Sıvı biyoyakıt imalatı', 1),
    (N'20.59', N'Başka yerde sınıflandırılmamış diğer kimyasal ürünlerin imalatı', 1),
    (N'20.60', N'Suni veya sentetik elyaf imalatı', 1),
    (N'21.10', N'Temel eczacılık ürünleri imalatı', 1),
    (N'21.20', N'Eczacılığa ilişkin preparatların (müstahzarların) imalatı', 1),
    (N'22.11', N'Kauçuk lastiklerin imalatı, lastiğe sırt geçirilmesi (kaplanması) ve yeniden işlenmesi ve iç lastik imalatı', 1),
    (N'22.12', N'Diğer kauçuk ürünlerin imalatı', 1),
    (N'22.21', N'Plastik tabaka, levha, tüp ve profil imalatı', 1),
    (N'22.22', N'Plastik ambalaj malzemeleri imalatı', 1),
    (N'22.23', N'Plastikten kapı ve pencere imalatı', 1),
    (N'22.24', N'Plastikten inşaat malzemeleri imalatı', 1),
    (N'22.25', N'Plastik ürünlerin işlenmesi ve bitirilmesi', 1),
    (N'22.26', N'Diğer plastik ürünlerin imalatı', 1),
    (N'23.11', N'Düz cam imalatı', 1),
    (N'23.12', N'Düz camın şekillendirilmesi ve işlenmesi', 1),
    (N'23.13', N'Çukur cam imalatı', 1),
    (N'23.14', N'Cam elyafı imalatı', 1),
    (N'23.15', N'Diğer camların imalatı ve işlenmesi (teknik amaçlı cam eşyalar dahil)', 1),
    (N'23.20', N'Ateşe dayanıklı (refrakter) ürünlerin imalatı', 1),
    (N'23.31', N'Seramik karo ve kaldırım taşları imalatı', 1),
    (N'23.32', N'Fırınlanmış kilden tuğla, karo ve inşaat malzemeleri imalatı', 1),
    (N'23.41', N'Seramik ev ve süs eşyaları imalatı', 1),
    (N'23.42', N'Seramik sıhhi ürünlerin imalatı', 1),
    (N'23.43', N'Seramik yalıtkanların (izolatörlerin) ve yalıtkan bağlantı parçalarının imalatı', 1),
    (N'23.44', N'Diğer teknik seramik ürünlerin imalatı', 1),
    (N'23.45', N'Diğer seramik ürünlerin imalatı', 1),
    (N'23.51', N'Çimento imalatı', 1),
    (N'23.52', N'Kireç ve alçı imalatı', 1),
    (N'23.61', N'İnşaat amaçlı beton ürünlerin imalatı', 1),
    (N'23.62', N'İnşaat amaçlı alçı ürünlerin imalatı', 1),
    (N'23.63', N'Hazır beton imalatı', 1),
    (N'23.64', N'Toz harç imalatı', 1),
    (N'23.65', N'Lif ve çimento karışımlı ürünlerin imalatı', 1),
    (N'23.66', N'Beton, çimento ve alçıdan diğer eşyaların imalatı', 1),
    (N'23.70', N'Taş ve mermerin kesilmesi, şekil verilmesi ve bitirilmesi', 1),
    (N'23.91', N'Aşındırıcı ürünlerin imalatı', 1),
    (N'23.99', N'Başka yerde sınıflandırılmamış metalik olmayan diğer mineral ürünlerin imalatı', 1),
    (N'24.10', N'Ana demir ve çelik ürünleri ile ferro alaşımların imalatı', 1),
    (N'24.20', N'Çelikten tüpler, borular, içi boş profiller ve benzeri bağlantı parçalarının imalatı', 1),
    (N'24.31', N'Barların soğuk çekilmesi', 1),
    (N'24.32', N'Dar şeritlerin soğuk haddelenmesi', 1),
    (N'24.33', N'Soğuk şekillendirme veya katlama', 1),
    (N'24.34', N'Tellerin soğuk çekilmesi', 1),
    (N'24.41', N'Değerli metal üretimi', 1),
    (N'24.42', N'Alüminyum üretimi', 1),
    (N'24.43', N'Kurşun, çinko ve kalay üretimi', 1),
    (N'24.44', N'Bakır üretimi', 1),
    (N'24.45', N'Demir dışı diğer metallerin üretimi', 1),
    (N'24.46', N'Nükleer yakıtların işlenmesi', 1),
    (N'24.51', N'Demir döküm', 1),
    (N'24.52', N'Çelik dökümü', 1),
    (N'24.53', N'Hafif metallerin dökümü', 1),
    (N'24.54', N'Diğer demir dışı metallerin dökümü', 1),
    (N'25.11', N'Metal yapı ve yapı parçaları imalatı', 1),
    (N'25.12', N'Metalden kapı ve pencere imalatı', 1),
    (N'25.21', N'Merkezi ısıtma radyatörleri, buhar jeneratörleri ve sıcak su kazanlarının (boylerleri) imalatı', 1),
    (N'25.22', N'Metalden diğer tank, rezervuar ve konteynerler imalatı', 1),
    (N'25.30', N'Silah ve mühimmat (cephane) imalatı', 1),
    (N'25.40', N'Metallerin dövülmesi, şekil verilmesi ve toz metalürjisi', 1),
    (N'25.51', N'Metallerin kaplanması', 1),
    (N'25.52', N'Metallerin ısıl işlemi', 1),
    (N'25.53', N'Metallerin makinede işlenmesi ve şekil verilmesi', 1),
    (N'25.61', N'Çatal-bıçak takımı ve diğer kesici aletlerin imalatı', 1),
    (N'25.62', N'Kilit ve menteşe imalatı', 1),
    (N'25.63', N'El aletleri, takım tezgahı uçları, testere ağızları vb. imalatı', 1),
    (N'25.91', N'Çelik varil ve benzer muhafazaların imalatı', 1),
    (N'25.92', N'Metalden hafif paketleme malzemeleri imalatı', 1),
    (N'25.93', N'Tel ürünleri, zincir ve yayların imalatı', 1),
    (N'25.94', N'Bağlantı malzemelerinin ve vida makinesi ürünlerinin imalatı', 1),
    (N'25.99', N'Başka yerde sınıflandırılmamış diğer fabrikasyon metal ürünlerin imalatı', 1),
    (N'26.11', N'Elektronik bileşenlerin imalatı', 1),
    (N'26.12', N'Yüklü elektronik kart imalatı', 1),
    (N'26.20', N'Bilgisayar ve bilgisayar çevre birimleri imalatı', 1),
    (N'26.30', N'İletişim ekipmanlarının imalatı', 1),
    (N'26.40', N'Tüketici elektroniği ürünlerinin imalatı', 1),
    (N'26.51', N'Ölçme, test ve seyrüsefer (navigasyon) amaçlı alet ve cihazların imalatı', 1),
    (N'26.52', N'Kol saatlerinin, masa ve duvar saatlerinin ve benzerlerinin imalatı', 1),
    (N'26.60', N'Işınlama, elektro medikal ve elektro terapi ile ilgili cihazların imalatı', 1),
    (N'26.70', N'Optik aletlerin, manyetik ve optik medyanın ve fotoğrafik ekipmanların imalatı', 1),
    (N'27.11', N'Elektrik motorları, jeneratörler ve transformatörlerin imalatı', 1),
    (N'27.12', N'Elektrik dağıtım ve kontrol cihazları imalatı', 1),
    (N'27.20', N'Akümülatör ve pil imalatı', 1),
    (N'27.31', N'Fiber optik kabloların imalatı', 1),
    (N'27.32', N'Diğer elektronik ve elektrikli teller ve kabloların imalatı', 1),
    (N'27.33', N'Kablolamada kullanılan gereçlerin imalatı', 1),
    (N'27.40', N'Aydınlatma ekipmanları imalatı', 1),
    (N'27.51', N'Elektrikli ev aletlerinin imalatı', 1),
    (N'27.52', N'Elektriksiz ev aletlerinin imalatı', 1),
    (N'27.90', N'Diğer elektrikli ekipmanların imalatı', 1),
    (N'28.11', N'Motor ve türbin imalatı (hava taşıtı, motorlu kara taşıtı ve motosiklet motorları hariç)', 1),
    (N'28.12', N'Akışkan gücü ile çalışan ekipmanların imalatı', 1),
    (N'28.13', N'Diğer pompaların ve kompresörlerin imalatı', 1),
    (N'28.14', N'Diğer musluk ve valf/vana imalatı', 1),
    (N'28.15', N'Rulman, dişli/dişli takımı, şanzıman ve tahrik elemanlarının imalatı', 1),
    (N'28.21', N'Fırınlar, sobalar ve sabit ev ısıtma ekipmanlarının imalatı', 1),
    (N'28.22', N'Kaldırma ve taşıma ekipmanları imalatı', 1),
    (N'28.23', N'Büro makine ve ekipmanları imalatı (bilgisayarlar ve çevre birimleri hariç)', 1),
    (N'28.24', N'Motorlu veya pnömatik (hava basınçlı) el aletlerinin imalatı', 1),
    (N'28.25', N'Ev dışı iklimlendirme ekipmanlarının imalatı', 1),
    (N'28.29', N'Başka yerde sınıflandırılmamış diğer genel amaçlı makinelerin imalatı', 1),
    (N'28.30', N'Tarım ve ormancılık makinelerinin imalatı', 1),
    (N'28.41', N'Metal şekillendirme makineleri ve metal işlemeye yönelik takım tezgahlarının imalatı', 1),
    (N'28.42', N'Diğer takım tezgahlarının imalatı', 1),
    (N'28.91', N'Metalürji makineleri imalatı', 1),
    (N'28.92', N'Maden, taş ocağı ve inşaat makineleri imalatı', 1),
    (N'28.93', N'Gıda, içecek ve tütün işleme makineleri imalatı', 1),
    (N'28.94', N'Tekstil, giyim eşyası ve deri üretiminde kullanılan makinelerin imalatı', 1),
    (N'28.95', N'Kağıt ve mukavva üretiminde kullanılan makinelerin imalatı', 1),
    (N'28.96', N'Plastik ve kauçuk makinelerinin imalatı', 1),
    (N'28.97', N'Katmanlı (eklemeli) imalat makineleri imalatı', 1),
    (N'28.99', N'Başka yerde sınıflandırılmamış diğer özel amaçlı makinelerin imalatı', 1),
    (N'29.10', N'Motorlu kara taşıtlarının imalatı', 1),
    (N'29.20', N'Motorlu kara taşıtları gövdesi ve karoseri (kaporta) imalatı; treyler (römork) ve yarı treyler (yarı römork) imalatı', 1),
    (N'29.31', N'Motorlu kara taşıtları için elektrik ve elektronik donanımların imalatı', 1),
    (N'29.32', N'Motorlu kara taşıtları için diğer parça ve aksesuarların imalatı', 1),
    (N'30.11', N'Sivil gemilerin ve yüzer yapıların inşası', 1),
    (N'30.12', N'Eğlence ve spor amaçlı teknelerin yapımı', 1),
    (N'30.13', N'Askeri gemilerin ve teknelerin inşası', 1),
    (N'30.20', N'Demir yolu lokomotifleri ve vagonlarının imalatı', 1),
    (N'30.31', N'Sivil hava ve uzay araçları ve ilgili makinelerin imalatı', 1),
    (N'30.32', N'Askeri hava ve uzay araçları ve ilgili makinelerin imalatı', 1),
    (N'30.40', N'Askeri kara savaş araçlarının imalatı', 1),
    (N'30.91', N'Motosiklet imalatı', 1),
    (N'30.92', N'Bisiklet ve engelli aracı imalatı', 1),
    (N'30.99', N'Başka yerde sınıflandırılmamış diğer ulaşım ekipmanlarının imalatı', 1),
    (N'31.00', N'Mobilya imalatı', 1),
    (N'32.11', N'Madeni para basımı', 1),
    (N'32.12', N'Mücevher ve benzeri eşyaların imalatı', 1),
    (N'32.13', N'İmitasyon (taklit) takılar ve ilgili eşyaların imalatı', 1),
    (N'32.20', N'Müzik aletleri imalatı', 1),
    (N'32.30', N'Spor malzemeleri imalatı', 1),
    (N'32.40', N'Oyun ve oyuncak imalatı', 1),
    (N'32.50', N'Tıbbi ve dişçilik ile ilgili araç ve gereçlerin imalatı', 1),
    (N'32.91', N'Süpürge ve fırça imalatı', 1),
    (N'32.99', N'Başka yerde sınıflandırılmamış diğer imalatlar', 1),
    (N'33.11', N'Fabrikasyon metal ürünlerin onarım ve bakımı', 1),
    (N'33.12', N'Makinelerin onarım ve bakımı', 1),
    (N'33.13', N'Elektronik ve optik ekipmanların onarım ve bakımı', 1),
    (N'33.14', N'Elektrikli ekipmanların onarım ve bakımı', 1),
    (N'33.15', N'Sivil gemilerin ve teknelerin onarım ve bakımı', 1),
    (N'33.16', N'Sivil hava taşıtları ve uzay araçlarının onarım ve bakımı', 1),
    (N'33.17', N'Diğer sivil ulaşım ekipmanlarının onarım ve bakımı', 1),
    (N'33.18', N'Askeri savaş araçlarının, gemilerin, teknelerin, hava ve uzay araçlarının onarım ve bakımı', 1),
    (N'33.19', N'Diğer ekipmanların onarım ve bakımı', 1),
    (N'33.20', N'Sanayi makine ve ekipmanlarının kurulumu', 1),
    (N'35.11', N'Yenilenemeyen kaynaklardan elektrik üretimi', 1),
    (N'35.12', N'Yenilenebilir kaynaklardan elektrik üretimi', 1),
    (N'35.13', N'Elektrik enerjisinin iletimi', 1),
    (N'35.14', N'Elektrik enerjisinin dağıtımı', 1),
    (N'35.15', N'Elektrik enerjisinin ticareti', 1),
    (N'35.16', N'Elektriğin depolanması', 1),
    (N'35.21', N'Gaz imalatı', 1),
    (N'35.22', N'Ana şebeke üzerinden gaz yakıtların dağıtımı', 1),
    (N'35.23', N'Ana şebeke üzerinden gaz ticareti', 1),
    (N'35.24', N'Gazın depolanması (şebeke tedarik hizmetlerinin bir parçası olarak)', 1),
    (N'35.30', N'Buhar ve iklimlendirme temini', 1),
    (N'35.40', N'Elektrik enerjisi ve doğal gaz aracılarının ve komisyoncularının faaliyetleri', 1),
    (N'36.00', N'Suyun toplanması, arıtılması ve dağıtılması', 1),
    (N'37.00', N'Kanalizasyon', 1),
    (N'38.11', N'Tehlikesiz atıkların toplanması', 1),
    (N'38.12', N'Tehlikeli atıkların toplanması', 1),
    (N'38.21', N'Materyallerin geri kazanımı', 1),
    (N'38.22', N'Enerji geri kazanımı', 1),
    (N'38.23', N'Diğer atık geri kazanımı', 1),
    (N'38.31', N'Enerji geri kazanımı olmaksızın atıkların yakılması', 1),
    (N'38.32', N'Atıkların düzenli veya kalıcı olarak depolanması', 1),
    (N'38.33', N'Diğer atıkların bertarafı', 1),
    (N'39.00', N'İyileştirme faaliyetleri ve diğer atık yönetimi hizmeti faaliyetleri', 1),
    (N'41.00', N'İkamet amaçlı olan ve ikamet amaçlı olmayan binaların inşaatı', 1),
    (N'42.11', N'Kara yolları ve otoyolların inşaatı', 1),
    (N'42.12', N'Demir yolları ve metroların inşaatı', 1),
    (N'42.13', N'Köprüler ve tünellerin inşaatı', 1),
    (N'42.21', N'Akışkanlar için hizmet projelerinin inşaatı', 1),
    (N'42.22', N'Elektrik ve telekomünikasyon için hizmet projelerinin inşaatı', 1),
    (N'42.91', N'Su projeleri inşaatı', 1),
    (N'42.99', N'Başka yerde sınıflandırılmamış bina dışı diğer yapılara ait projelerin inşaatı', 1),
    (N'43.11', N'Yıkım işleri (binaların ve diğer yapıların yıkılması ve sökülmesi)', 1),
    (N'43.12', N'Şantiyenin hazırlanması', 1),
    (N'43.13', N'Test sondajı ve delme', 1),
    (N'43.21', N'Elektrik tesisatı', 1),
    (N'43.22', N'Sıhhi tesisat, ısıtma ve iklimlendirme tesisatı', 1),
    (N'43.23', N'Yalıtım tesisatı', 1),
    (N'43.24', N'Diğer inşaat tesisatı', 1),
    (N'43.31', N'Sıva işleri', 1),
    (N'43.32', N'Doğrama tesisatı', 1),
    (N'43.33', N'Yer ve duvar kaplama', 1),
    (N'43.34', N'Boya ve cam işleri', 1),
    (N'43.35', N'İnşaatlardaki diğer bütünleyici ve tamamlayıcı işler', 1),
    (N'43.41', N'Çatı işleri', 1),
    (N'43.42', N'Bina inşaatlarındaki diğer özel inşaat faaliyetleri', 1),
    (N'43.50', N'Bina dışı yapılardaki özel inşaat faaliyetleri', 1),
    (N'43.60', N'Özel inşaat hizmetleri için aracılık hizmeti faaliyetleri', 1),
    (N'43.91', N'Duvarcılık ve tuğla, briket vb. döşeme faaliyetleri', 1),
    (N'43.99', N'Başka yerde sınıflandırılmamış diğer özel inşaat faaliyetleri', 1),
    (N'46.11', N'Tarımsal ham maddelerin, canlı hayvanların, tekstil ham maddelerinin ve yarı mamul malların toptan satışı ile ilgili aracıların faaliyetleri', 1),
    (N'46.12', N'Yakıtların, maden cevherlerinin, metallerin ve endüstriyel kimyasalların toptan satışı ile ilgili aracıların faaliyetleri', 1),
    (N'46.13', N'Kereste ve inşaat malzemelerinin toptan satışı ile ilgili aracıların faaliyetleri', 1),
    (N'46.14', N'Makine, sanayi araç ve gereçleri ile deniz ve hava taşıtlarının toptan satışı ile ilgili aracıların faaliyetleri', 1),
    (N'46.15', N'Mobilya, ev eşyaları, hırdavat ve madeni eşyaların toptan satışı ile ilgili aracıların faaliyetleri', 1),
    (N'46.16', N'Tekstil, giysi, kürk, ayakkabı ve deri eşyaların toptan satışı ile ilgili aracıların faaliyetleri', 1),
    (N'46.17', N'Gıda, içecek ve tütün toptan satışı ile ilgili aracıların faaliyetleri', 1),
    (N'46.18', N'Belirli diğer ürünlerin toptan satışı ile ilgili aracıların faaliyetleri', 1),
    (N'46.19', N'Uzmanlaşmamış toptan ticaret ile ilgili aracıların faaliyetleri', 1),
    (N'46.21', N'Tahıl, işlenmemiş tütün, tohum ve hayvan yemi toptan ticareti', 1),
    (N'46.22', N'Çiçeklerin ve bitkilerin toptan ticareti', 1),
    (N'46.23', N'Canlı hayvanların toptan ticareti', 1),
    (N'46.24', N'Ham deri, post ve deri toptan ticareti', 1),
    (N'46.31', N'Meyve ve sebzelerin toptan ticareti', 1),
    (N'46.32', N'Et ve et ürünleri ile balık ve balık ürünlerinin toptan ticareti', 1),
    (N'46.33', N'Süt ürünleri, yumurta ve yenilebilir sıvı ve katı yağların toptan ticareti', 1),
    (N'46.34', N'İçeceklerin toptan ticareti', 1),
    (N'46.35', N'Tütün ürünlerinin toptan ticareti', 1),
    (N'46.36', N'Şeker, çikolata ve şekerleme toptan ticareti', 1),
    (N'46.37', N'Kahve, çay, kakao ve baharat toptan ticareti', 1),
    (N'46.38', N'Diğer gıda maddelerinin toptan ticareti', 1),
    (N'46.39', N'Uzmanlaşmamış gıda, içecek ve tütün toptan ticareti', 1),
    (N'46.41', N'Tekstil ürünlerinin toptan ticareti', 1),
    (N'46.42', N'Giysi ve ayakkabı toptan ticareti', 1),
    (N'46.43', N'Elektrikli ev aletleri toptan ticareti', 1),
    (N'46.44', N'Porselen ve cam eşya ile temizlik maddelerinin toptan ticareti', 1),
    (N'46.45', N'Parfüm ve kozmetik ürünlerinin toptan ticareti', 1),
    (N'46.46', N'Eczacılık ve medikal ürünlerin toptan ticareti', 1),
    (N'46.47', N'Ev, büro ve dükkan mobilyası ile halı ve aydınlatma ekipmanlarının toptan ticareti', 1),
    (N'46.48', N'Saat ve mücevher toptan ticareti', 1),
    (N'46.49', N'Diğer ev eşyalarının toptan ticareti', 1),
    (N'46.50', N'Bilgi ve iletişim teknolojisi teçhizatının toptan ticareti', 1),
    (N'46.61', N'Tarımsal amaçlı makine ve ekipmanlar ile aksam ve parçalarının toptan ticareti', 1),
    (N'46.62', N'Takım tezgahlarının toptan ticareti', 1),
    (N'46.63', N'Madencilik, bina ve bina dışı inşaat makinelerinin toptan ticareti', 1),
    (N'46.64', N'Diğer makine ve ekipmanların toptan ticareti', 1),
    (N'46.71', N'Motorlu kara taşıtlarının toptan ticareti', 1),
    (N'46.72', N'Motorlu kara taşıtlarının parça ve aksesuarlarının toptan ticareti', 1),
    (N'46.73', N'Motosikletlerin, motosiklet parçalarının ve aksesuarlarının toptan ticareti', 1),
    (N'46.81', N'Katı, sıvı ve gazlı yakıtlar ile bunlarla ilgili ürünlerin toptan ticareti', 1),
    (N'46.82', N'Metallerin ve metal cevherlerinin toptan ticareti', 1),
    (N'46.83', N'Ağaç, inşaat malzemesi ve sıhhi teçhizat toptan ticareti', 1),
    (N'46.84', N'Hırdavat, sıhhi tesisat ve ısıtma tesisatı malzemelerinin toptan ticareti', 1),
    (N'46.85', N'Kimyasal ürünlerin toptan ticareti', 1),
    (N'46.86', N'Diğer ara ürünlerin toptan ticareti', 1),
    (N'46.87', N'Atık ve hurda toptan ticareti', 1),
    (N'46.89', N'Başka yerde sınıflandırılmamış uzmanlaşmış diğer toptan ticaret', 1),
    (N'46.90', N'Uzmanlaşmamış toptan ticaret', 1),
    (N'47.11', N'Uzmanlaşmamış gıda, içecek veya tütün ağırlıklı perakende ticaret', 1),
    (N'47.12', N'Uzmanlaşmamış diğer perakende ticaret', 1),
    (N'47.21', N'Meyve ve sebze perakende ticareti', 1),
    (N'47.22', N'Et ve et ürünlerinin perakende ticareti', 1),
    (N'47.23', N'Balık, kabuklu hayvanlar ve yumuşakçaların perakende ticareti', 1),
    (N'47.24', N'Ekmek, pasta ve şekerleme perakende ticareti', 1),
    (N'47.25', N'İçeceklerin perakende ticareti', 1),
    (N'47.26', N'Tütün ürünlerinin perakende ticareti', 1),
    (N'47.27', N'Diğer gıda ürünlerinin perakende ticareti', 1),
    (N'47.30', N'Otomotiv yakıtının perakende ticareti', 1),
    (N'47.40', N'Bilgi ve iletişim teknolojisi teçhizatının perakende ticareti', 1),
    (N'47.51', N'Tekstil ürünleri perakende ticareti', 1),
    (N'47.52', N'Hırdavat, inşaat malzemeleri, boya ve cam perakende ticareti', 1),
    (N'47.53', N'Halı, kilim, duvar ve yer kaplamalarının perakende ticareti', 1),
    (N'47.54', N'Elektrikli ev aletlerinin perakende ticareti', 1),
    (N'47.55', N'Mobilya, aydınlatma teçhizatı, sofra takımları ve diğer ev eşyalarının perakende ticareti', 1),
    (N'47.61', N'Kitap perakende ticareti', 1),
    (N'47.62', N'Gazeteler ile diğer periyodik yayınlar ve kırtasiye ürünlerinin perakende ticareti', 1),
    (N'47.63', N'Spor malzemelerinin perakende ticareti', 1),
    (N'47.64', N'Oyunlar ve oyuncakların perakende ticareti', 1),
    (N'47.69', N'Başka yerde sınıflandırılmamış kültür ve eğlence (rekreasyon) ürünlerinin perakende ticareti', 1),
    (N'47.71', N'Giyim eşyalarının perakende ticareti', 1),
    (N'47.72', N'Ayakkabı ve deri eşyaların perakende ticareti', 1),
    (N'47.73', N'Eczacılık ürünlerinin perakende ticareti', 1),
    (N'47.74', N'Medikal ve ortopedik ürünlerin perakende ticareti', 1),
    (N'47.75', N'Kozmetik ve kişisel bakım malzemelerinin perakende ticareti', 1),
    (N'47.76', N'Çiçek, bitki, gübre, ev hayvanları ve ev hayvanları yemleri perakende ticareti', 1),
    (N'47.77', N'Saat ve mücevher perakende ticareti', 1),
    (N'47.78', N'Diğer yeni malların perakende ticareti', 1),
    (N'47.79', N'Kullanılmış malların perakende ticareti', 1),
    (N'47.81', N'Motorlu kara taşıtlarının perakende ticareti', 1),
    (N'47.82', N'Motorlu kara taşıtlarının parça ve aksesuarlarının perakende ticareti', 1),
    (N'47.83', N'Motosikletlerin, motosiklet parçalarının ve aksesuarlarının perakende ticareti', 1),
    (N'47.91', N'Uzmanlaşmamış perakende ticaret için aracılık hizmeti faaliyetleri', 1),
    (N'47.92', N'Uzmanlaşmış perakende ticaret için aracılık hizmeti faaliyetleri', 1),
    (N'49.11', N'Demir yolu ile yolcu taşımacılığı (ağır raylı sistem)', 1),
    (N'49.12', N'Diğer demir yolu ile yolcu taşımacılığı', 1),
    (N'49.20', N'Demir yolu ile yük taşımacılığı', 1),
    (N'49.31', N'Kara yoluyla tarifeli yolcu taşımacılığı', 1),
    (N'49.32', N'Kara yoluyla tarifesiz yolcu taşımacılığı', 1),
    (N'49.33', N'Sürücülü araç ile isteğe bağlı yolcu taşıma hizmeti faaliyetleri', 1),
    (N'49.34', N'Teleferik ve telesiyejlerle yolcu taşımacılığı', 1),
    (N'49.39', N'Başka yerde sınıflandırılmamış kara taşımacılığı ile yapılan diğer yolcu taşımacılığı', 1),
    (N'49.41', N'Kara yolu ile yük taşımacılığı', 1),
    (N'49.42', N'Ev ve iş yerlerine verilen taşımacılık hizmetleri', 1),
    (N'49.50', N'Boru hattı taşımacılığı', 1),
    (N'50.10', N'Deniz ve kıyı sularında yolcu taşımacılığı', 1),
    (N'50.20', N'Deniz ve kıyı sularında yük taşımacılığı', 1),
    (N'50.30', N'İç sularda yolcu taşımacılığı', 1),
    (N'50.40', N'İç sularda yük taşımacılığı', 1),
    (N'51.10', N'Hava yolu ile yolcu taşımacılığı', 1),
    (N'51.21', N'Hava yolu ile yük taşımacılığı', 1),
    (N'51.22', N'Uzay taşımacılığı', 1),
    (N'52.10', N'Depolama ve ambarlama', 1),
    (N'52.21', N'Kara taşımacılığını destekleyici hizmet faaliyetleri', 1),
    (N'52.22', N'Su yolu taşımacılığını destekleyici hizmet faaliyetleri', 1),
    (N'52.23', N'Hava yolu taşımacılığını destekleyici hizmet faaliyetleri', 1),
    (N'52.24', N'Kargo yükleme boşaltma (elleçleme) hizmetleri', 1),
    (N'52.25', N'Lojistik hizmet faaliyetleri', 1),
    (N'52.26', N'Taşımacılığa yönelik diğer destekleyici faaliyetler', 1),
    (N'52.31', N'Yük taşımacılığına yönelik aracılık hizmeti faaliyetleri', 1),
    (N'52.32', N'Yolcu taşımacılığına yönelik aracılık hizmeti faaliyetleri', 1),
    (N'53.10', N'Evrensel hizmet yükümlülüğü altında postacılık faaliyetleri', 1),
    (N'53.20', N'Diğer posta ve kurye faaliyetleri', 1),
    (N'53.30', N'Posta ve kurye faaliyetlerine yönelik aracılık hizmeti faaliyetleri', 1),
    (N'55.10', N'Oteller ve benzeri konaklama yerleri', 1),
    (N'55.20', N'Tatil ve diğer kısa süreli konaklama yerleri', 1),
    (N'55.30', N'Kamp alanları ve karavan parkları', 1),
    (N'55.40', N'Konaklama için aracılık hizmeti faaliyetleri', 1),
    (N'55.90', N'Diğer konaklama yerleri', 1),
    (N'56.11', N'Lokantaların faaliyetleri', 1),
    (N'56.12', N'Seyyar yemek hizmeti faaliyetleri', 1),
    (N'56.21', N'Özel günlerde dışarıya yemek hizmeti sunan işletmelerin faaliyetleri', 1),
    (N'56.22', N'Sözleşmeli yemek hizmeti faaliyetleri ve diğer yemek hizmeti faaliyetleri', 1),
    (N'56.30', N'İçecek sunum hizmetleri', 1),
    (N'56.40', N'Yiyecek ve içecek hizmetleri faaliyetleri için aracılık hizmeti faaliyetleri', 1),
    (N'58.11', N'Kitapların yayımı', 1),
    (N'58.12', N'Gazetelerin yayımlanması', 1),
    (N'58.13', N'Dergi ve süreli yayınların yayımlanması', 1),
    (N'58.19', N'Diğer yayımcılık faaliyetleri (yazılım programlarının yayımı hariç)', 1),
    (N'58.21', N'Video oyunlarının yayımlanması', 1),
    (N'58.29', N'Diğer yazılım programlarının yayımlanması', 1),
    (N'59.11', N'Sinema filmi, video ve televizyon programları yapım faaliyetleri', 1),
    (N'59.12', N'Sinema filmi, video ve televizyon programları çekim sonrası faaliyetleri', 1),
    (N'59.13', N'Sinema filmi ve video dağıtım faaliyetleri', 1),
    (N'59.14', N'Sinema filmi gösterim faaliyetleri', 1),
    (N'59.20', N'Ses kaydı ve müzik yayıncılığı faaliyetleri', 1),
    (N'60.10', N'Radyo yayıncılığı ve ses dağıtım faaliyetleri', 1),
    (N'60.20', N'Televizyon programcılığı, yayıncılığı ve video dağıtım faaliyetleri', 1),
    (N'60.31', N'Haber ajanslarının faaliyetleri', 1),
    (N'60.39', N'Diğer içerik dağıtım faaliyetleri', 1),
    (N'61.10', N'Kablolu, kablosuz ve uydu telekomünikasyon faaliyetleri', 1),
    (N'61.20', N'Telekomünikasyon ürünlerinin yeniden satışı ve telekomünikasyon için aracılık hizmeti faaliyetleri', 1),
    (N'61.90', N'Diğer telekomünikasyon faaliyetleri', 1),
    (N'62.10', N'Bilgisayar programlama faaliyetleri', 1),
    (N'62.20', N'Bilgisayar danışmanlığı ve bilgisayar birimleri (sistemleri) yönetimi faaliyetleri', 1),
    (N'62.90', N'Diğer bilgi teknolojisi ve bilgisayar hizmet faaliyetleri', 1),
    (N'63.10', N'Bilgi işlem altyapısı, veri işleme, barındırma ve ilgili faaliyetler', 1),
    (N'63.91', N'Web arama portalı faaliyetleri', 1),
    (N'63.92', N'Diğer bilgi hizmeti faaliyetleri', 1),
    (N'64.11', N'Merkez bankası faaliyetleri', 1),
    (N'64.19', N'Diğer parasal aracılık faaliyetleri', 1),
    (N'64.21', N'Holding şirketlerinin faaliyetleri', 1),
    (N'64.22', N'Finansman tedarik şirketlerinin faaliyetleri', 1),
    (N'64.31', N'Para piyasası ve para piyasası dışı yatırım fonlarının faaliyetleri', 1),
    (N'64.32', N'Servet yönetim şirketleri (trustlar), emlak ve acente hesaplarının faaliyetleri', 1),
    (N'64.91', N'Finansal kiralama', 1),
    (N'64.92', N'Diğer kredi verme faaliyetleri', 1),
    (N'64.99', N'Başka yerde sınıflandırılmamış diğer finansal hizmet faaliyetleri (Sigorta ve emeklilik fonları hariç)', 1),
    (N'65.11', N'Hayat sigortası', 1),
    (N'65.12', N'Hayat sigortası dışındaki sigortalar', 1),
    (N'65.20', N'Reasürans', 1),
    (N'65.30', N'Emeklilik fonları', 1),
    (N'66.11', N'Finansal piyasaların yönetimi', 1),
    (N'66.12', N'Menkul kıymetler ve emtia sözleşmeleri aracılığı', 1),
    (N'66.19', N'Finansal hizmetlere yardımcı diğer faaliyetler (Sigorta ve emeklilik fonları hariç)', 1),
    (N'66.21', N'Risk ve hasar değerlemesi', 1),
    (N'66.22', N'Sigorta acentelerinin ve aracılarının faaliyetleri', 1),
    (N'66.29', N'Başka yerde sınıflandırılmamış sigorta ve emeklilik fonlarına yardımcı faaliyetler', 1),
    (N'66.30', N'Fon yönetimi faaliyetleri', 1),
    (N'68.11', N'Kendine ait gayrimenkulün alınıp satılması', 1),
    (N'68.12', N'Yapı projelerinin geliştirilmesi', 1),
    (N'68.20', N'Kendine ait veya kiralanan gayrimenkulün kiralanması ve işletilmesi', 1),
    (N'68.31', N'Gayrimenkul faaliyetleri için aracılık hizmeti faaliyetleri', 1),
    (N'68.32', N'Bir ücret veya sözleşme temeline dayalı olan diğer gayrimenkul faaliyetleri', 1),
    (N'69.10', N'Hukuk faaliyetleri', 1),
    (N'69.20', N'Muhasebe, defter tutma ve denetim faaliyetleri; vergi danışmanlığı', 1),
    (N'70.10', N'İdare merkezi faaliyetleri', 1),
    (N'70.20', N'İşletme ve diğer idari danışmanlık faaliyetleri', 1),
    (N'71.11', N'Mimarlık faaliyetleri', 1),
    (N'71.12', N'Mühendislik faaliyetleri ve ilgili teknik danışmanlık', 1),
    (N'71.20', N'Teknik test ve analiz faaliyetleri', 1),
    (N'72.10', N'Doğal bilimler ve mühendislikle ilgili araştırma ve deneysel geliştirme faaliyetleri', 1),
    (N'72.20', N'Sosyal bilimlerle ve beşeri bilimlerle ilgili araştırma ve deneysel geliştirme faaliyetleri', 1),
    (N'73.11', N'Reklam ajanslarının faaliyetleri', 1),
    (N'73.12', N'Çeşitli medya reklamları için alan ve zamanın bir ücret veya sözleşmeye dayalı olarak satışı', 1),
    (N'73.20', N'Piyasa ve kamuoyu araştırma faaliyetleri', 1),
    (N'73.30', N'Halkla ilişkiler ve iletişim faaliyetleri', 1),
    (N'74.11', N'Endüstriyel ürün ve moda tasarımı faaliyetleri', 1),
    (N'74.12', N'Grafik tasarım ve görsel iletişim faaliyetleri', 1),
    (N'74.13', N'İç tasarım faaliyetleri', 1),
    (N'74.14', N'Diğer uzmanlaşmış tasarım faaliyetleri', 1),
    (N'74.20', N'Fotoğrafçılık faaliyetleri', 1),
    (N'74.30', N'Tercüme ve sözlü tercüme faaliyetleri', 1),
    (N'74.91', N'Patent aracılığı ve pazarlama hizmeti faaliyetleri', 1),
    (N'74.99', N'Başka yerde sınıflandırılmamış diğer mesleki, bilimsel ve teknik faaliyetler', 1),
    (N'75.00', N'Veterinerlik hizmetleri', 1),
    (N'77.11', N'Motorlu hafif kara taşıtlarının ve arabaların kiralanması ve leasingi', 1),
    (N'77.12', N'Kamyonların kiralanması ve leasingi', 1),
    (N'77.21', N'Eğlence ve spor eşyalarının kiralanması ve leasingi', 1),
    (N'77.22', N'Diğer kişisel eşyaların ve ev eşyalarının kiralanması ve leasingi', 1),
    (N'77.31', N'Tarımsal makine ve ekipmanların kiralanması ve leasingi', 1),
    (N'77.32', N'Bina ve bina dışı inşaatlarda kullanılan makine ve ekipmanların kiralanması ve leasingi', 1),
    (N'77.33', N'Büro makine, ekipman ve bilgisayarlarının kiralanması ve leasingi', 1),
    (N'77.34', N'Su yolu taşımacılığı ekipmanının kiralanması ve leasingi', 1),
    (N'77.35', N'Hava taşımacılığı araçlarının kiralanması ve leasingi', 1),
    (N'77.39', N'Başka yerde sınıflandırılmamış diğer makine, ekipman ve maddi malların kiralanması ve leasingi', 1),
    (N'77.40', N'Fikri mülkiyet haklarının ve benzer ürünlerin leasingi (Telif hakkı alınmış olan çalışmalar hariç)', 1),
    (N'77.51', N'Otomobillerin, motorlu karavanların ve römorkların kiralanması ve leasingine ilişkin aracılık hizmeti faaliyetleri', 1),
    (N'77.52', N'Diğer maddi varlıkların ve finans dışı maddi olmayan varlıkların kiralanması ve leasingi için aracılık hizmeti faaliyetleri', 1),
    (N'78.10', N'İş bulma acentelerinin faaliyetleri', 1),
    (N'78.20', N'Geçici iş bulma acenteleri ile diğer insan kaynaklarının sağlanması faaliyetleri', 1),
    (N'79.11', N'Seyahat acentesi faaliyetleri (yolcu taşımacılığı için olanlar hariç)', 1),
    (N'79.12', N'Tur operatörü faaliyetleri', 1),
    (N'79.90', N'Diğer rezervasyon hizmetleri ve ilgili faaliyetler', 1),
    (N'80.01', N'Soruşturma ve özel güvenlik faaliyetleri', 1),
    (N'80.09', N'Başka yerde sınıflandırılmamış güvenlik faaliyetleri', 1),
    (N'81.10', N'Tesis bünyesindeki kombine destek hizmetleri', 1),
    (N'81.21', N'Binaların genel temizliği', 1),
    (N'81.22', N'Diğer bina ve endüstriyel temizlik faaliyetleri', 1),
    (N'81.23', N'Diğer temizlik faaliyetleri', 1),
    (N'81.30', N'Çevre düzenlemesi ve bakımı faaliyetleri', 1),
    (N'82.10', N'Büro yönetimi ve destek faaliyetleri', 1),
    (N'82.20', N'Çağrı merkezlerinin faaliyetleri', 1),
    (N'82.30', N'Kongre ve ticari gösteri organizasyonu', 1),
    (N'82.40', N'Başka yerde sınıflandırılmamış işletme destek hizmetleri için aracılık hizmeti faaliyetleri', 1),
    (N'82.91', N'Tahsilat ve kredi kayıt bürolarının faaliyetleri', 1),
    (N'82.92', N'Paketleme faaliyetleri', 1),
    (N'82.99', N'Başka yerde sınıflandırılmamış diğer işletme destek hizmeti faaliyetleri', 1),
    (N'84.11', N'Genel kamu idaresi faaliyetleri', 1),
    (N'84.12', N'Sağlık, eğitim, kültürel hizmetler ve diğer sosyal hizmetlerin düzenlenmesi', 1),
    (N'84.13', N'İş etkinliğinin artırılmasına yönelik katkı ve düzenleme faaliyetleri', 1),
    (N'84.21', N'Dışişleri ile ilgili hizmetler', 1),
    (N'84.22', N'Savunma faaliyetleri', 1),
    (N'84.23', N'Adalet ve yargı organlarının faaliyetleri', 1),
    (N'84.24', N'Kamu düzeni ve güvenliği ile ilgili faaliyetler', 1),
    (N'84.25', N'İtfaiye hizmetleri', 1),
    (N'84.30', N'Zorunlu sosyal güvenlik faaliyetleri', 1),
    (N'85.10', N'Okul öncesi eğitim', 1),
    (N'85.20', N'İlköğretim', 1),
    (N'85.31', N'Genel ortaöğretim', 1),
    (N'85.32', N'Mesleki orta öğretim', 1),
    (N'85.33', N'Ortaöğretim sonrası yükseköğretim derecesinde olmayan eğitim', 1),
    (N'85.40', N'Yükseköğretim', 1),
    (N'85.51', N'Spor ve eğlence (rekreasyon) eğitimi', 1),
    (N'85.52', N'Kültürel eğitim', 1),
    (N'85.53', N'Sürücü kursu faaliyetleri', 1),
    (N'85.59', N'Başka yerde sınıflandırılmamış diğer eğitim', 1),
    (N'85.61', N'Kurslara ve eğitmenlere yönelik aracılık hizmeti faaliyetleri', 1),
    (N'85.69', N'Başka yerde sınıflandırılmamış eğitim destek faaliyetleri', 1),
    (N'86.10', N'Hastane hizmetleri', 1),
    (N'86.21', N'Genel hekimlik uygulama faaliyetleri', 1),
    (N'86.22', N'Tıp uzmanlarının faaliyetleri', 1),
    (N'86.23', N'Dişçilik ile ilgili uygulama ve bakım faaliyetleri', 1),
    (N'86.91', N'Tanı amaçlı görüntüleme hizmetleri ve tıbbi laboratuvar faaliyetleri', 1),
    (N'86.92', N'Ambulansla hasta taşıma', 1),
    (N'86.93', N'Psikolog ve psikoterapistlerin faaliyetleri (tıp doktorları hariç)', 1),
    (N'86.94', N'Hemşirelik ve ebelik faaliyetleri', 1),
    (N'86.95', N'Fizyoterapi hizmetleri (tıp doktorları dışında yetkili kişilerce sağlanan fizyoterapi, ergoterapi vb. alanlardaki hizmetler) (hastane dışı)', 1),
    (N'86.96', N'Geleneksel, tamamlayıcı ve alternatif tıp faaliyetleri', 1),
    (N'86.97', N'Tıp, dişçilik ve diğer insan sağlığı hizmetlerine yönelik aracılık hizmeti faaliyetleri', 1),
    (N'86.99', N'Başka yerde sınıflandırılmamış diğer insan sağlığı faaliyetleri', 1),
    (N'87.10', N'Hemşireli yatılı bakım faaliyetleri', 1),
    (N'87.20', N'Zihinsel rahatsızlığı veya madde kullanımı teşhisi olan kişilere yönelik yatılı bakım faaliyetleri', 1),
    (N'87.30', N'Yaşlılara veya bedensel engellilere yönelik yatılı bakım faaliyetleri', 1),
    (N'87.91', N'Yatılı bakım faaliyetleri için aracılık hizmeti faaliyetleri', 1),
    (N'87.99', N'Başka yerde sınıflandırılmamış diğer yatılı bakım faaliyetleri', 1),
    (N'88.10', N'Yaşlılar veya engelliler için barınacak yer sağlanmaksızın verilen sosyal hizmetler', 1),
    (N'88.91', N'Çocuk gündüz bakım (kreş) faaliyetleri', 1),
    (N'88.99', N'Başka yerde sınıflandırılmamış barınacak yer sağlanmaksızın verilen diğer sosyal yardım faaliyetleri', 1),
    (N'90.11', N'Edebiyat eseri oluşturma ve müzikal kompozisyon faaliyetleri', 1),
    (N'90.12', N'Görsel sanatlar yaratıcılık faaliyetleri', 1),
    (N'90.13', N'Diğer sanatsal yaratıcılık faaliyetleri', 1),
    (N'90.20', N'Gösteri sanatları faaliyetleri', 1),
    (N'90.31', N'Sanat tesislerinin ve alanlarının (mekanlarının) işletilmesi', 1),
    (N'90.39', N'Sanat ve gösteri sanatlarına yönelik diğer destek faaliyetleri', 1),
    (N'91.11', N'Kütüphane faaliyetleri', 1),
    (N'91.12', N'Arşiv faaliyetleri', 1),
    (N'91.21', N'Müze ve koleksiyonculuk faaliyetleri', 1),
    (N'91.22', N'Tarihi alan ve anıt faaliyetleri', 1),
    (N'91.30', N'Kültürel mirasın konservasyonu, restorasyonu ve diğer destek faaliyetleri', 1),
    (N'91.41', N'Botanik ve hayvanat bahçesi faaliyetleri', 1),
    (N'91.42', N'Tabiatı koruma faaliyetleri', 1),
    (N'92.00', N'Kumar ve müşterek bahis faaliyetleri', 1),
    (N'93.11', N'Spor tesislerinin işletilmesi', 1),
    (N'93.12', N'Spor kulüplerinin faaliyetleri', 1),
    (N'93.13', N'Fitness merkezlerinin faaliyetleri', 1),
    (N'93.19', N'Başka yerde sınıflandırılmamış spor faaliyetleri', 1),
    (N'93.21', N'Eğlence parkları ve tema parklarının faaliyetleri', 1),
    (N'93.29', N'Başka yerde sınıflandırılmamış eğlence ve dinlence (rekreasyon) faaliyetleri', 1),
    (N'94.11', N'İş ve işveren kuruluşlarının faaliyetleri', 1),
    (N'94.12', N'Profesyonel meslek kuruluşlarının faaliyetleri', 1),
    (N'94.20', N'Sendikaların faaliyetleri', 1),
    (N'94.91', N'Dini kuruluşların faaliyetleri', 1),
    (N'94.92', N'Siyasi kuruluşların faaliyetleri', 1),
    (N'94.99', N'Başka yerde sınıflandırılmamış diğer üye olunan kuruluşların faaliyetleri', 1),
    (N'95.10', N'Bilgisayarların ve iletişim ekipmanlarının onarım ve bakımı', 1),
    (N'95.21', N'Tüketici elektroniği ürünlerinin onarım ve bakımı', 1),
    (N'95.22', N'Evde kullanılan cihazlar ile ev ve bahçe gereçlerinin onarım ve bakımı', 1),
    (N'95.23', N'Ayakkabı ve deri eşyaların onarım ve bakımı', 1),
    (N'95.24', N'Mobilya ve ev döşemelerinin onarım ve bakımı', 1),
    (N'95.25', N'Saatlerin ve mücevherlerin onarım ve bakımı', 1),
    (N'95.29', N'Başka yerde sınıflandırılmamış kişisel eşyaların ve ev eşyalarının onarım ve bakımı', 1),
    (N'95.31', N'Motorlu kara taşıtlarının onarım ve bakımı', 1),
    (N'95.32', N'Motosikletlerin onarım ve bakımı', 1),
    (N'95.40', N'Bilgisayarların, kişisel eşyalar ve ev eşyalarının, motorlu kara taşıtlarının ve motosikletlerin onarım ve bakımı için aracılık hizmeti faaliyetleri', 1),
    (N'96.10', N'Tekstil ve kürk ürünlerinin yıkanması ve temizlenmesi', 1),
    (N'96.21', N'Kuaförlük ve berberlik faaliyetleri', 1),
    (N'96.22', N'Güzellik bakımı faaliyetleri', 1),
    (N'96.23', N'Günlük spa, sauna ve buhar banyosu faaliyetleri', 1),
    (N'96.30', N'Cenaze işleri ile ilgili faaliyetler', 1),
    (N'96.40', N'Kişisel hizmetler için aracılık hizmeti faaliyetleri', 1),
    (N'96.91', N'Ev içi kişisel hizmet faaliyetlerinin sağlanması', 1),
    (N'96.99', N'Başka yerde sınıflandırılmamış diğer kişisel hizmet faaliyetleri', 1),
    (N'97.00', N'Ev içi çalışan personelin işverenleri olarak hanehalklarının faaliyetleri', 1),
    (N'98.10', N'Hanehalkları tarafından kendi kullanımlarına yönelik olarak üretilen ayrım yapılmamış mallar', 1),
    (N'98.20', N'Hanehalkları tarafından kendi kullanımlarına yönelik olarak üretilen ayrım yapılmamış hizmetler', 1),
    (N'99.00', N'Uluslararası örgütler ve temsilciliklerinin faaliyetleri', 1)
) AS kaynak (Kod, Ad, Aktif)
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.Nace AS mevcut
    WHERE mevcut.Kod = kaynak.Kod
);

DECLARE @EklenenKayitSayisi int = @@ROWCOUNT;

COMMIT TRANSACTION;

SELECT @EklenenKayitSayisi AS EklenenKayitSayisi,
       (SELECT COUNT(*) FROM dbo.Nace WHERE Aktif = 1) AS ToplamAktifNaceSayisi;